<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: stream/simple.proto

namespace TestStream;

use Spiral\RoadRunner\GRPC;

interface StreamServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "testStream.StreamService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param MessageIn $in
    * @return MessageOut
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SimpleMethod(
        GRPC\ContextInterface $ctx,
        MessageIn $in,
    ): MessageOut;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GRPC\StreamReader $reader
    * @return MessageOut
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ClientStreamMethod(
        GRPC\ContextInterface $ctx,
        #[GRPC\Attribute\Input(MessageIn::class)] GRPC\StreamReader $reader,
    ): MessageOut;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param MessageIn $in
    * @param GRPC\StreamWriter $writer
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ServerStreamMethod(
        GRPC\ContextInterface $ctx,
        MessageIn $in,
        #[GRPC\Attribute\Output(MessageOut::class)] GRPC\StreamWriter $writer,
    ): void;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GRPC\StreamReader $reader
    * @param GRPC\StreamWriter $writer
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function BidiStreamMethod(
        GRPC\ContextInterface $ctx,
        #[GRPC\Attribute\Input(MessageIn::class)] GRPC\StreamReader $reader,
        #[GRPC\Attribute\Output(MessageOut::class)] GRPC\StreamWriter $writer,
    ): void;
}
